x-ruby-defaults: &golang_defaults
  restart: always
  command: bash -c "cat /golang_service > cmd.sh && chmod +x /cmd.sh && /cmd.sh"
  working_dir: /data/apps
  command: sleep 200s

  configs:
    - source: golang_service

services:

  golang1.17:
    container_name: golang1.17
    image: golang:1.17
    volumes: 
      - golang1.17:/data/apps
    <<: *golang_defaults

volumes:
  golang1.17:
  golang1.18:

configs:
  golang_service:
    file: ./config/golang/service.sh