x-java-defaults: &java_defaults
  restart: always
  command: bash -c "cat /java_service > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
  working_dir: /var/www/html
  configs:
    - source: java_service

services:

  java8:
    container_name: java8
    image: openjdk:8
    volumes: 
      - java8:/var/www/html
    <<: *java_defaults

volumes:
  java8:
  java8.0:
  java7.4:
  java7.3:
  java7.2:
  java7.1:
  java7.0:
  java5.6:

configs:
  java_service:
    file: ./config/java/service.sh