x-ruby-defaults: &php_defaults
  restart: always
  command: bash -c "cat /php_service > /cmd.sh && chmod +x /cmd.sh && /cmd.sh"
  working_dir: /var/www/html
  configs:
    - source: php_service

services:
  php7.4:
    container_name: php7.4
    image: php:7.4-apache
    volumes: 
      - php7.4:/var/www/html
    <<: *php_defaults

volumes:
  php7.4:

configs:
  php_service:
    file: ./config/php/service.sh