services:
  mysql:
    image: mysql:5.7
    container_name: ${APP_NAME}-mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
     - mysql_data:/var/lib/mysql
     - mysql_conf:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: 123456

  phpmyadmin:
      image: phpmyadmin:latest
      container_name: ${APP_NAME}-phpmyadmin
      environment:
       - PMA_ARBITRARY=1
       - PMA_ABSOLUTE_URI=$APP_URL
       - UPLOAD_LIMIT=$APP_UPLOAD_LIMIT
      restart: always
      ports:
       - 9091:80

volumes:
  mysql_data:
  mysql_conf: