services:

  consul:
    container_name: $APP_NAME-consul
    image: consul
    ports:
      - 8500:8500
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    network_mode: "host"

volumes:
  db:
  app: